language: node_js
cache:
  yarn: true
  directories:
    - node_modules
node_js:
  - "8.10.0"
script:
  - yarn test
  - yarn lint
  - yarn build
after_success:
  - yarn run coverage
  - if [ "$TRAVIS_BRANCH" = "master" -a "$TRAVIS_PULL_REQUEST" = "false" ]; then yarn run deploy; fi
after_script: yarn run coveralls
